---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
  - name: collect
    image: publicawesome/stargaze:0.9.1
    commands:
      - sh ./check.sh
  - name: runner
    image: publicawesome/stargaze:0.9.1
    detach: true
    commands:
      - sh ./run.sh
  - name: check_runner
    image: alpine:3
    commands:
      - apk add curl
      - sleep 50
      - curl http://runner:26657/status
trigger:
  event:
    - pull_request

---
kind: signature
hmac: 9096fcc3237475ef398457d007ef115071c9f681f830845f09dbe3f9a0c9a0f3

...
