---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
trigger:
  event:
    - pull_request

---
kind: signature
hmac: f221b3fc21cc9cf950232a043c2844a97f2f94be69c3f0da23c0b1127bae8edf

...
