---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
---
kind: signature
hmac: bdb16f48412ef5dc136d3c5dc49ab34d3bb50ab1d2b319e1df99fe7f0830081d

...
