---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
---
kind: signature
hmac: 19f68084c85f2522c29137bcd17ab55994fb2d557318ac7c28d5984d21b48cc0

...
